baseURL: "https://clonemasteruwu.github.io"
languageCode: en-us
title: clonemasteruwu
theme: PaperMod
params:
  math: true

  defaultTheme: auto 

  homeInfoParams:
    Title: The notes
    Content: of unorthodox solutions

  socialIcons:
    - name: "github"
      url: "https://github.com/clonemasteruwu"

    - name: "codeforces"
      url: "https://codeforces.com/profile/clonemasteruwu"

    - name: "leetcode"
      url: "https://leetcode.com/clonemasterUwU/"
      
    - name: "leetcode"
      url: "https://leetcode.com/clonemaasteruwu/"